AIConfig:
  TextGeneration:
    max_tokens: 2048
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    Models:
      gpt-4:
        name: "gpt-4"
        temperature: 0.7
        rate:
          input_token_price: 5
          output_token_price: 50

      gpt-4o:
        name: "gpt-4o"
        temperature: 0.7
        text_default: true
        vision_defaul: true
        rate:
          input_token_price: 1
          output_token_price: 10
          input_pixel_price: 0.0001

  ImageGeneration:
    output_image_size: "512x512"
    Models:
      dalle-3:
        name: "dalle-3"
        temperature: 0.7
        image_generation_default: true
        rate:
          input_token_price: 0.0001
          output_pixel_price: 10

  AudioRecognition:
    Models:
      whisper:
        name: "whisper-1"
        temperature: 0.7
        audio_recognition_default: true
        rate:
          input_audio_price_per_second: 0.0001
          output_token_price: 1
