AIConfig:
  text_generation:
    max_tokens: 2048
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    Models:
      gpt-4o:
        name: "gpt-4o"
        temperature: 0.7
        is_default: true
        rate:
          input_token_price: 1
          output_token_price: 10
          input_pixel_price: 0.0001

  image_generation:
    output_image_size: "512x512"
    Models:
      dalle-3:
        name: "dalle-3"
        temperature: 0.7
        is_default: true
        rate:
          input_token_price: 0.0001
          output_pixel_price: 10

  audio_recognition:
    Models:
      whisper:
        name: "whisper-1"
        temperature: 0.7
        is_default: true
        rate:
          input_audio_price_per_second: 0.0001
          output_token_price: 1

  vision:
    Models:
      gpt-4o:
        name: "gpt-4o"
        is_default: true
        rate:
          input_pixel_price: 0.0001
          output_token_price: 1
